h0: hw3_0.y
	bison -d hw3_0.y
	gcc hw3_0.tab.c -o hw3_0
h1: hw3_1.y
	bison -d hw3_1.y
	gcc hw3_1.tab.c -o hw3_1
h2: hw3_2.y
	bison -d hw3_2.y
	gcc hw3_2.tab.c -o hw3_2
h3: hw3_3.y
	bison -d hw3_3.y
	gcc hw3_3.tab.c -o hw3_3
h4: hw3_4.y
	bison -d hw3_4.y
	gcc hw3_4.tab.c -o hw3_4
clean:
	rm hw3_1
	rm hw3_2
	rm hw3_3
	rm hw3_4
	rm *.tab.*